const BRASSY22_SERVER_ID = '7a494b4b-647d-481d-89d1-beb7e6295669';
const EVAL_BOT_NAME = 'eval-bot';

export function buildOrchestratorPrompt(moduleName: string, promptName: string): string {
  return [
    'You are a senior Takaro module developer and orchestrator.',
    'Your task is to build, deploy, test, and clean up one Takaro module.',
    'Execute every step below without asking for clarification.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 0 — KNOWN ISSUES',
    '══════════════════════════════════════════════════════════',
    `Read the resource takaro://known-issues/${promptName}.`,
    'If it lists known errors, avoid repeating them in your implementation.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 1 — ANALYSE THE SPEC',
    '══════════════════════════════════════════════════════════',
    'Read the module specification provided in the user message.',
    'Identify every component: commands, hooks, cronjobs, shared functions.',
    'Decide whether to delegate:',
    '  • DELEGATE if: ≥3 commands, OR ≥2 independent hooks/cronjobs, OR multiple distinct subsystems.',
    '  • BUILD DIRECTLY if: ≤2 total components.',
    '',
    'Write a brief decomposition plan (one line per component) before proceeding.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 2 — SCAFFOLD',
    '══════════════════════════════════════════════════════════',
    `Call scaffold_module with the module name "${moduleName}".`,
    'This creates the directory structure. Do not write any files yet.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 3 — BUILD',
    '══════════════════════════════════════════════════════════',
    '',
    'IF DELEGATING (complex module):',
    '  Spawn one Task subagent per component or logical group IN PARALLEL.',
    '  Every subagent MUST follow this exact prompt (fill in the placeholders):',
    '',
    '  ┌──────────────────────────────────────────────────────────────────────────┐',
    `  │ You are implementing one component of the Takaro module "${moduleName}". │`,
    '  │ The module is already scaffolded — do NOT call scaffold_module.          │',
    '  │                                                                          │',
    '  │ YOUR COMPONENT: {componentName}                                          │',
    '  │ TYPE: {command | hook | cronjob | function}                              │',
    '  │ SPEC: {paste the relevant section of the module specification}           │',
    '  │                                                                          │',
    '  │ INSTRUCTIONS:                                                            │',
    '  │ 1. Read takaro://module-template for the required code pattern           │',
    '  │    (import header, async function main(), await main()).                 │',
    '  │ 2. Read takaro://api-reference for available takaro.* methods            │',
    '  │    and the shape of the data object.                                     │',
    '  │ 3. Write your source file using write_module_file:                       │',
    '  │      commands  → src/commands/{name}.js                                  │',
    '  │      hooks     → src/hooks/{eventName}.js                                │',
    '  │      cronjobs  → src/cronjobs/{name}.js                                  │',
    '  │      functions → src/functions/{name}.js                                 │',
    '  │ 4. YOUR FINAL MESSAGE must be ONLY a raw JSON object — no prose,        │',
    '  │    no markdown, no explanation. Example:                                 │',
    '  │    {                                                                     │',
    '  │      "commands": {                                                       │',
    '  │        "hello": { "name": "hello", "description": "...",                │',
    '  │          "arguments": [] }                                               │',
    '  │      }                                                                   │',
    '  │    }                                                                     │',
    '  │    Include only the keys relevant to your component                      │',
    '  │    (commands / hooks / cronJobs / functions).                            │',
    '  │    Do NOT include name, description, configSchema, or permissions.       │',
    '  │                                                                          │',
    '  │ Do NOT call write_module_json, push_module, or install_module.          │',
    '  └──────────────────────────────────────────────────────────────────────────┘',
    '',
    '  Wait for ALL subagent Tasks to complete before continuing to STEP 4.',
    '',
    'IF BUILDING DIRECTLY (≤2 components):',
    '  Read takaro://module-template and takaro://api-reference.',
    '  Write all source files with write_module_file.',
    '  Keep your module.json fragments in mind for STEP 4.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 4 — ASSEMBLE module.json  ← YOU MUST DO THIS',
    '══════════════════════════════════════════════════════════',
    'After ALL subagents have finished, you MUST call write_module_json.',
    'Do not skip this step. Do not proceed to STEP 5 without completing it.',
    '',
    'How to assemble:',
    '  1. Each subagent returned a JSON object in its final message.',
    '     Parse each one and merge their "commands", "hooks", "cronJobs",',
    '     and "functions" keys into one combined object.',
    '  2. If a subagent did not return valid JSON, call list_module_files and',
    '     read_module_file to infer the fragment from the file it wrote.',
    '  3. Call write_module_json with the fully merged object:',
    '     {',
    `       "name": "${moduleName}",`,
    '       "description": "<one-line description from the spec>",',
    '       "configSchema": { <all config fields from the spec, or {} if none> },',
    '       "permissions": [ <all permissions from the spec, or [] if none> ],',
    '       "commands":  { <merged from all fragments> },',
    '       "hooks":     { <merged from all fragments> },',
    '       "cronJobs":  { <merged from all fragments> },',
    '       "functions": { <merged from all fragments> }',
    '     }',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 5 — PUSH',
    '══════════════════════════════════════════════════════════',
    'Call push_module.',
    'Record the returned moduleId and latestVersionId — required for later steps.',
    'If push_module returns a validation error, fix the module.json schema and push again.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 6 — INSTALL & TEST',
    '══════════════════════════════════════════════════════════',
    `1. install_module(moduleId, latestVersionId, gameServerId:"${BRASSY22_SERVER_ID}")`,
    `2. bot_action(action:"create", botName:"${EVAL_BOT_NAME}")`,
    `3. list_players(gameServerId:"${BRASSY22_SERVER_ID}", onlineOnly:true)`,
    '   → find the bot\'s playerId. If not visible, wait ~5s and retry once.',
    '4. For each command in the module:',
    `     a. get_command_prefix(gameServerId:"${BRASSY22_SERVER_ID}")`,
    '     b. trigger_command(gameServerId, playerId, message:"{prefix}{commandName}")',
    '     c. poll_events(eventName:"command-executed", afterTimestamp from trigger_command)',
    '     d. Confirm success=true in the response.',
    '5. For cronjob-only or hook-only modules: installation success is sufficient.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 7 — FIX LOOP (maximum 3 attempts)',
    '══════════════════════════════════════════════════════════',
    'A test fails when: poll_events returns success=false, poll_events times out,',
    'or trigger_command itself errors.',
    '',
    'When a test fails you MUST attempt a fix. The ONLY reasons to skip fixing are:',
    '  • You have already made 3 fix attempts, OR',
    '  • get_failed_events shows a pure infrastructure error (game server unreachable,',
    '    Takaro API down, network timeout) with no indication your code caused it.',
    'Everything else — syntax error, wrong API call, bad argument schema, missing await,',
    'wrong command name, incorrect variable key — is fixable. Fix it.',
    '',
    'Fix procedure:',
    `  1. get_failed_events — read the full error to identify the root cause.`,
    `  2. uninstall_module(moduleId, gameServerId:"${BRASSY22_SERVER_ID}")`,
    '  3. Fix the affected source file(s) with write_module_file.',
    '     Update module.json if the schema changed (write_module_json).',
    '  4. push_module → record the new latestVersionId.',
    '  5. Return to STEP 6 and retest.',
    '',
    'Do NOT proceed to cleanup while fix attempts remain and the error is in your code.',
    '',
    '══════════════════════════════════════════════════════════',
    'STEP 8 — CLEANUP (always run, even on failure)',
    '══════════════════════════════════════════════════════════',
    `uninstall_module(moduleId, gameServerId:"${BRASSY22_SERVER_ID}")`,
    `bot_action(action:"delete", botName:"${EVAL_BOT_NAME}")`,
  ].join('\n');
}
